//! Build script.
//!
//! Two responsibilities:
//!
//! 1. Verify the active `rustc` meets vrd's minimum supported version.
//! 2. Pre-compute the 256-bin Ziggurat tables for the half-normal
//!    distribution and emit them to `$OUT_DIR/ziggurat_tables.rs`. The
//!    table generation runs once per build and produces three checked
//!    arrays (`K[256]` `u32`, `W[256]` `f64`, `F[256]` `f64`) used by
//!    [`vrd::ziggurat`] to sample `Random::normal()` in ~4 ns/sample.
//!
//! Generating at build time (rather than checking in 768 hand-written
//! magic constants) means a single deterministic recurrence - Marsaglia
//! & Tsang (2000), *J. Stat. Software* 5(8) - is the source of truth. A
//! typo in the recurrence is caught immediately by the crate's golden
//! vector test; there is no way for individual table entries to silently
//! drift.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process;

fn main() {
    check_min_rustc("1.56");
    emit_ziggurat_tables();
}

/// Aborts the build if the active `rustc` is older than
/// `min_version`. Called from `main` before any code generation.
fn check_min_rustc(min_version: &str) {
    match version_check::is_min_version(min_version) {
        Some(true) => {}
        _ => {
            eprintln!("vrd requires Rustc version >= {min_version}");
            process::exit(1);
        }
    }
}

/// Generates the Ziggurat tables for the half-normal distribution with
/// `N = 256` strips and writes them to `$OUT_DIR/ziggurat_tables.rs`.
///
/// The layout follows Marsaglia & Tsang (2000) with the 2³¹ scale used
/// by the canonical C reference: signed-32-bit sampling lets the sign
/// bit of `hz` carry the symmetry of the full normal for free.
///
/// Recurrence (with `R` = right edge of the rightmost strip and `V` =
/// per-strip area):
///
/// ```text
///   X[N-1] = R
///   X[i]   = sqrt(-2 ln (V/X[i+1] + exp(-X[i+1]²/2)))   for i = N-2 .. 1
///   K[0]   = (R / q) · 2³¹      where q = V / exp(-R²/2)
///   K[i+1] = (X[i+1] / X[i+2]) · 2³¹
///   K[1]   = 0                                              (forces fallback)
///   W[0]   = q / 2³¹
///   W[i]   = X[i] / 2³¹
///   F[0]   = 1                                              (= h(0))
///   F[i]   = exp(-X[i]²/2)
/// ```
fn emit_ziggurat_tables() {
    const N: usize = 256;
    const R: f64 = 3.654_152_885_361_009;
    const V: f64 = 4.928_673_233_705_38e-3;
    const M: f64 = (1u64 << 31) as f64;

    let mut k = [0u32; N];
    let mut w = [0.0f64; N];
    let mut f = [0.0f64; N];

    let mut dn = R;
    let mut tn = dn;
    let h = |x: f64| (-0.5 * x * x).exp();
    let q = V / h(dn);

    k[0] = (dn / q * M) as u32;
    k[1] = 0;
    w[0] = q / M;
    w[N - 1] = dn / M;
    f[0] = 1.0;
    f[N - 1] = h(dn);

    let mut i = N - 2;
    while i >= 1 {
        let next = (-2.0 * (V / dn + h(dn)).ln()).sqrt();
        dn = next;
        k[i + 1] = ((dn / tn) * M) as u32;
        tn = dn;
        f[i] = h(dn);
        w[i] = dn / M;
        i -= 1;
    }

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("ziggurat_tables.rs");
    let mut file =
        fs::File::create(&dest).expect("create ziggurat_tables.rs");

    writeln!(
        file,
        "// Auto-generated by build.rs. Do not edit by hand."
    )
    .unwrap();
    writeln!(
        file,
        "/// Right edge of the rightmost rectangular strip."
    )
    .unwrap();
    writeln!(file, "pub(crate) const ZIG_NORM_R: f64 = {:?};", R)
        .unwrap();
    let _ = V;
    write_u32_table(&mut file, "ZIG_NORM_K", &k);
    write_f64_table(&mut file, "ZIG_NORM_W", &w);
    write_f64_table(&mut file, "ZIG_NORM_F", &f);

    println!("cargo:rerun-if-changed=build.rs");
}

/// Emits a `pub(crate) static NAME: [u32; N] = [...];` declaration
/// to `out`, used to write the Ziggurat `K` threshold table.
fn write_u32_table(out: &mut fs::File, name: &str, table: &[u32]) {
    writeln!(
        out,
        "/// {name}: bin-acceptance threshold table; see build.rs."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static {name}: [u32; {}] = [",
        table.len()
    )
    .unwrap();
    for chunk in table.chunks(8) {
        write!(out, "    ").unwrap();
        for v in chunk {
            write!(out, "{}u32, ", v).unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Emits a `pub(crate) static NAME: [f64; N] = [...];` declaration
/// to `out`, used to write the Ziggurat `W` and `F` lookup tables.
fn write_f64_table(out: &mut fs::File, name: &str, table: &[f64]) {
    writeln!(
        out,
        "/// {name}: f64 lookup table for the Ziggurat half-normal; see build.rs."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static {name}: [f64; {}] = [",
        table.len()
    )
    .unwrap();
    for chunk in table.chunks(4) {
        write!(out, "    ").unwrap();
        for v in chunk {
            write!(out, "{:?}f64, ", v).unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "];").unwrap();
}
