[package]
authors = ["The vrd contributors <contact@vrdlib.one>"]
build = "build.rs"
categories = ['Algorithms', 'Encoding','Parser implementations','Data structures']
description = "A Rust library for generating random and pseudo-random numbers based on the Mersenne Twister algorithm"
documentation = "https://docs.rs/vrd"
edition = "2021"
exclude = [
    "/.git/*",
    "/.github/*",
    "/.gitignore",
    "/.vscode/*"
]
homepage = "https://vrdlib.one"
include = [
    "/CONTRIBUTING.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/examples/**",
    "/README.md",
    "/src/**",
    "/tests/**",
    "/xtask/**",
]
keywords = ["entropy", "rand", "random-number", "random", "vrd"]
license = "MIT OR Apache-2.0"
name = "vrd"
readme = "README.md"
repository = "https://github.com/sebastienrousseau/vrd"
rust-version = "1.71.1"
version = "0.0.5"

[workspace]
members = ["xtask"]

[[bench]]
name = "benchmark"
harness = false
path = "benches/criterion.rs"

[profile.bench]
debug = true

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.12"
criterion = "0.5.1"

[lib]
crate-type = ["lib"]
name = "vrd"
path = "src/lib.rs"

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false
panic = "abort"
rpath = false
strip = "symbols"

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
