name: 🧪 Audit

on:
  push:
    branches:
      - feat/vrd
  pull_request:
    branches:
      - feat/vrd
  release:
    types: [created]

jobs:
  dependencies:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - uses: actions/checkout@master
      - name: Audit dependencies
        run: cargo audit
